### ISSUE TITLE
Need to make custom fields available in api connect

### ISSUE THREAD

**Issue by metin** [ibm-apiconnect/devportal#1]
Hi,
Is there a way  to make fields in "Account settings" available in api connect? Like, getting email address for the client id in the api connect using gateway script.

**Comment by chrisdudley** [comment]
The client ID is a credential that belongs to an application, the application belongs to a developer organization.
The developer organization has an owner and members.
It is the owner and the members who have email addresses, not the application or the developer organization.
I am not sure if gateway script can access that information - I'll check.

Certainly any custom fields you add to the user accounts in the portal will not be accessible in APIC, e.g. if you added a new field "department name" that information does not currently leave the portal.

**Comment by metin** [comment]
Yeah, I am aware of the hierarchy. I am asking this because this info ends up in apic. I am assuming these are made available in APIC by the portal. 
```
client.app.name
client.app.id
client.app.secret
client.org.id
client.org.name
```
I was curious if I could make more of that stuff available in here. 

Am I making a wrong assumption?

**Comment by chrisdudley** [comment]
I don't think there is currently a gateway script context variable with that information.
The developer organization ID and name are available, and using the devorg ID you could call the api manager portal API to get the org owner email address.

**Comment by chrisdudley** [comment]
Using client.org.id you could call this:
http://www.ibm.com/support/knowledgecenter/SSMNED_5.0.0/com.ibm.apic.apirest.doc/rest_op_portal_orgs__orgID_GET.html
However authentication might be an issue - not sure how you'd authenticate to that API from within gateway script.

**Comment by chrisdudley** [comment]
If you want extra context variables available in gateway script then the best idea is probably to raise an RFE with details on which ones youd like and an example use case:
https://www.ibm.com/developerworks/rfe/

**Comment by metin** [comment]
Yeah, I'll probably be able to auth with dev portal admin user. 

How does the current `client*` variables become available in the api connect?

**Comment by chrisdudley** [comment]
dev portal admin user wont be able to auth on that API above I'm afraid. Despite the name "portal api" its not part of the portal, its an API from APIC for use by a portal.

**Comment by fsofronis** [comment]
I would like to remote the Client ID "Reset" button from IBM API Developer. I've tried various ways (adding rules, etc.) but nothing worked. Do you have any idea how this button can be removed?

**Comment by chrisdudley** [comment]
@fsofronis please dont ask questions on existing issues - especially when they are completely unrelated.

**Comment by chrisdudley** [comment]
For the original question, this is being worked on and should be available later this year.
