### ISSUE TITLE
Disabling Primary Buttons

### ISSUE THREAD

**Issue by dachser-pb** [ibm-apiconnect/devportal#10]
Hello APIC Developer Team,

during customization I noticed that when disabling a primary button (e.g. when performing customized validations on a token title using jQuery), the buttons background does not change if the _disabled_ property is added. Only the pointer style changes.

This behavior is clearly against the [carbon design conventions](https://www.carbondesignsystem.com/components/form/usage).

You can reproduce it by adding a _disabled_ property to the submit button on the page /application/new.

Can this be fixed?

Regards,
Patrick

**Comment by redlanne** [comment]
Thanks for bringing this to our attention - we have raised this internally and taking a look.
regards,
Anne

**Comment by chrisdudley** [comment]
Just noticed we never closed this - this was fixed in APIC 10.0.1.1.
