### ISSUE TITLE
Optimize Examples for String Fields with format: date

### ISSUE THREAD

**Issue by dachser-pb** [ibm-apiconnect/devportal#12]
Dear APIC Developer Team,
when a field is described as
```
type: string
format: date-time
```
then a correct example is generated in the Portal: "2017-01-27T12:56:38.965Z"

```
type: string
format: date
```
generates something like "Fri May 22". Following the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types) fields with format date should also follow RFC3339 and be YYYY-MM-DD.

In fact our APIs will return dates always in YYYY-MM-DD and not like "Fri May 22".

Thanks a lot for your feedback!

**Comment by chrisdudley** [comment]
Hiya, thanks for the bug report - fortunately this is one we had already found through internal testing. 
The fix will be delivered in a few weeks time in 10.0.1.1.

If you find any other problems with the examples generated for particular parameters please do let us know - we're always trying to improve the quality of both the API rendering and the examples generated.
