### ISSUE TITLE
Add Markdown Support for Product Descriptions

### ISSUE THREAD

**Issue by dachser-pb** [ibm-apiconnect/devportal#13]
Dear APIC Developer Team
in V10 Markdown is no longer parsed in Product Descriptions (like in v5) however for API Description in fact Markdown is supported.
This is not logical. Will there again be support for Markdown in Product Descriptions? If yes, when is it planned?
Thanks for info and Best Regards

**Comment by chrisdudley** [comment]
There should be markdown for product descriptions already present.
There is not markdown support for the summary field - thats a plaintext summary designed for use on a card or list view.
But the description field does allow markdown.

It might be that the API Manager UI has labelled the summary field as description in the UI? Check the source view in the editor and check the markdown is in the description field. If you still have an issue please let me know.
But my suspicion is that what you think is the description is actually the summary field.

**Comment by dachser-pb** [comment]
Hello Chris, thanks for the quick response.

Your assumption is right. Would it be possible to add the description field also in the Product Designer? As of today it is only possible to change description in the Source View.
I changed in the source and can confirm that markdown works for the description.

**Comment by chrisdudley** [comment]
I would totally agree with you that is the correct fix, but I am afraid you'll need to raise a SupportCase or RFE for that to happen, as the team owning that code aren't involved with this repository. I'll try contacting them, but if you can raise the PMR/RFE too then that will definitely add more weight.
