### ISSUE TITLE
HTML Markup Rendering in Security Definitions

### ISSUE THREAD

**Issue by dachser-pb** [ibm-apiconnect/devportal#14]
I noticed that on the API overview HTML is not possible in the security definition:
![image](https://user-images.githubusercontent.com/74193758/101148415-e04c9980-361d-11eb-8eac-aa698844441e.png)

However it is interpreted at the page for path/operation:
![image](https://user-images.githubusercontent.com/74193758/101148507-fce8d180-361d-11eb-9ac2-cd6369977a90.png)

It should be the same behavior on both levels. Personally I would prefer to have the HTML support, but if that is not possible it should also not be possible on the path/operation site.

Thanks for your feedback.

**Comment by chrisdudley** [comment]
We will support markdown in the descriptions but not HTML - there's simply far too much risk for XSS with HTML.

Thanks for the bug report though, we'll take a look.

**Comment by chrisdudley** [comment]
I've tried the latest code and it is at least consistent now - in that the HTML works in both places. Which I'm not sure is correct - we'll check on that from an XSS perspective, but at least its already consistent :-)

**Comment by redlanne** [comment]
markdown does support html - so it should be rendered in both the overview and operation.   On latest code I can see it is rendered for both what version are you currently on?

**Comment by dachser-pb** [comment]
In the Portal I can see
IBM API Connect Version
10.0.1.0
20200916-2031

**Comment by chrisdudley** [comment]
Strongly recommend upgrading to 10.0.1.1 and that might solve the problem, but im not 100% sure as I'm not sure when we fixed that issue and whether it was before 10.0.1.1 was frozen or not.
