### ISSUE TITLE
Incorrect text.... 'the' is repeated the the message "'Unable to sign in. This may be because the the credentials prov......"

### ISSUE THREAD

**Issue by prashantsinalkar** [ibm-apiconnect/devportal#15]
https://github.com/ibm-apiconnect/devportal/blob/c17a6773428fc89ddd718f842c7c8b994075b06c/auth_apic/src/Form/ApicUserLoginForm.php#L440

**Comment by redlanne** [comment]
This code is maintained in an internal repo so the change needs to be made there.  Thank you for bringing this to our attention.
