### ISSUE TITLE
How to develop portal

### ISSUE THREAD

**Issue by zhangjingyang** [ibm-apiconnect/devportal#19]
Now the client wants me to help them develop a customized theme, but the portal is deployed in a container, they cannot provide me with the operation permissions of the portal file, which is very difficult to debug. Do you have any experience and methods you can share?

**Comment by chrisdudley** [comment]
You will never be allowed to edit files in the container. You can create custom modules and themes but you cannot edit any file we ship.

The knowledge center has docs on how to create custom themes etc. 

Could you be a bit more specific with your question?
