### ISSUE TITLE
Any step by step instruction to integrate with Drupal 8?

### ISSUE THREAD

**Issue by ashutosh-srijan** [ibm-apiconnect/devportal#21]
Tried to use the modules with Drupal 8.9 but not sure how it will be configured properly.

Is there a step by step instruction that can be referred?

**Comment by chrisdudley** [comment]
This repository provides the source code for the APIC developer portal.
The modules will only work deployed as part of an APIC deployment - they will not work when added to a custom or local drupal installation.

APIC itself moved to Drupal 8.9 ages ago so the modules already work with that version of Drupal.

But just to be very clear - you cannot just add these modules to an existing Drupal installation, it will not work.

**Comment by ashutosh-srijan** [comment]
Got it thanks for the clarification.
