### ISSUE TITLE
Portal New Account Approval feature

### ISSUE THREAD

**Issue by marehem** [ibm-apiconnect/devportal#22]
There is a feature in APIC v.5 Developer Portal for forcing the Admin Approval for any new accounts created in the Portal.
this feature is not available in APIC v.2018.
I know this feature "account approval" is only when Portal Delegated User Registry "PDUR" is selected and this feature is no longer available in v.2018.

So, please how can I achieve the same behavior, require admin approval for Portal new created accounts, in APIC v.2018.

**Comment by chrisdudley** [comment]
It isn't possible to do approvals for accounts in apic v2018. There is no way to do it.

The capability is being added to apic v10 right now so your only option really is to plan to upgrade to apic v10 in a couple of months time.
