### ISSUE TITLE
Error during profile installation process [APIC_v5]

### ISSUE THREAD

**Issue by pedelgado** [ibm-apiconnect/devportal#23]
Aflter fulfilling all requirements in the development environment (contrib modules, libraries...) and executing the installation of the install profile it throws the following error during the installation process.

`Home Installation tasksVerify requirements(done)Set up database(done)Install profile(active)Configure siteConfigure languagesImport translationsConfigure API ManagementFinished SQLSTATE[42S22]: Column not found: 1054 Unknown column 'i18n_mode' in 'field list'.`

**Comment by chrisdudley** [comment]
Correct. It won't work anywhere other than in an apic developer portal server.

I'm afraid that's all that is supported.
We do not support running the code on custom drupal installs.
