### ISSUE TITLE
Issue with APIC 5.0.8.11

### ISSUE THREAD

**Issue by sue032** [ibm-apiconnect/devportal#24]
Hello APIC Developer Team,

After patched APIC to 5.0.8.11, we get this exception:

Uncaught TypeError: Cannot read property 'resolveReferences' of undefined
    at Object.attach (js_uyXAulrjlN_MYoE7iWHgnGQX5SF4RIfydA7CXdnOpL0.js:4072)

The fail is on this line in api.js:
         window.refResolver.resolveReferences(window.apiJson[0]).then(function(expandedapiJson) {

Any chance/idea on a fix for this?

Thanks a lot,
Sue

**Comment by chrisdudley** [comment]
You have apparently overridden the api node template.
If you override templates then there is a responsibility to check in every update to see what changes are made in the supplied templates and incorporate them in your overrides too. Failure to do so leads to issues like this.

Compare your override template with the supplied one here: https://github.com/ibm-apiconnect/devportal/blob/APIC_v5/ibm_apim/templates/node--api.tpl.php

I suspect you'll spot the missing lines to load the javascript files which is what is leading to the problem you're seeing.

This is not a product defect, I'm afraid this is a direct result from your customisations.

**Comment by sue032** [comment]
Thanks Chris. Checked https://github.com/ibm-apiconnect/devportal/blob/APIC_v5/ibm_apim/templates/node--api.tpl.php, the latest template seems for APIC 5.0.8.10. My portal worked on APIC 5.0.8.10 and has issue on APIC 5.0.8.11.

Where can I find the template for APIC 5.0.8.11?

**Comment by chrisdudley** [comment]
It hasn't changed. Compare your template with that one.
