### ISSUE TITLE
Rewrite strings inside js explorer

### ISSUE THREAD

**Issue by shumod** [ibm-apiconnect/devportal#27]
Hello APIC Developer Team!

How to rewrite some strings inside apiconnect-explorer tag? (template /apic_api/templates/node--api.html.twig)
With Drupal interface translation it's not possible. I can rewrite strings by patch in app/nls/*.json files, but maybe there is a better solution?

**Comment by chrisdudley** [comment]
It is not possible to do that. We absolutely will not support any patching of any file we ship. You will find that those changes will be completely lost on upgrades and may break the upgrade entirely.

It is explicitly stated in the documentation that modifying any file that we ship is a violation of your support agreement. I would *strongly* advise you cease doing so immediately.

As normal, if there is missing functionality then please raise an RFE.
