### ISSUE TITLE
Notification duration

### ISSUE THREAD

**Issue by sue032** [ibm-apiconnect/devportal#28]
Is there a setting in the devportal that I can use to define the expiry of the notifications so the notifications will disappear from the list after sometime?
Is there an API that I can use to delete a notification or clear all of the notifications of an org?

**Comment by chrisdudley** [comment]
What notifications are you referring to ? Have you got a screenshot ?

**Comment by redlanne** [comment]
If you are referring to APIC v10.0.3/v10.0.1.4 and want to expire the notifications this can be set by following this https://www.ibm.com/docs/en/api-connect/10.0.x?topic=tasks-configuring-notifications-event-log-settings

otherwise as Chris asks please provide screenshot and APIC version

**Comment by sue032** [comment]
Thanks Chris and Anne, 
We use APIC v5.0.8.12. The above link posted by Anne is exactly what I refer to, but I can not find **_Configuration > System > IBM APIC Notifications Settings_**  or **_Retention Days_**. 
Is it also possible for APIC v5? Is the default Retention Days also 30 days for APIC v5?

**Comment by redlanne** [comment]
I don't believe it was configurable for v5 - we added this setting when implementing this functionality in v10.

**Comment by chrisdudley** [comment]
Correct. Not an option in v5. You need to be looking at upgrade to v10 as APIC v5 is approaching the end of its life.
