### ISSUE TITLE
Disable IP restrictions for user login

### ISSUE THREAD

**Issue by sue032** [ibm-apiconnect/devportal#29]
I've accidentally added an invalid IP address to the administrator Allowed IP range, and I can not login as admin to the portal now.

Is there any other way I can Disable IP restrictions, e.g. via API, CLI?

**Comment by chrisdudley** [comment]
This is not an APIC support channel. 

If you have APIC support questions you need to raise a support case.

You can always disable the module via drush, in this case I suspect its the 'restrict_by_ip' module.

**Comment by sidshetty** [comment]
@sue032 I know this is closed and might be resolved by now. You can use CLI to update the table restrict_by_ip and change/update IP values or empty the table to remove restrictions if you don't want to disable the module and remove restrictions for all IDs.

**Comment by chrisdudley** [comment]
Worth saying that direct database access is NEVER supported - but its your risk to take.
APIC v10 has a portaladmin CLI which allows access to CLI equivalents of many drupal functions, and experienced drupal users might recognise many of them as wrappers to the drush functions!
