### ISSUE TITLE
modules for drupal 8

### ISSUE THREAD

**Issue by magiccreater** [ibm-apiconnect/devportal#3]
When can we except all module updated  for drupal 8?

**Comment by chrisdudley** [comment]
They're available now in the APIC v2018 developer portal - I've just not published the source code here, which is purely my fault.
I'll try and get that done ASAP.

Note that the APIC v5 developer portal is based on Drupal v7 and will always only be compatible with Drupal v7.
APIC v2018 uses Drupal v8 (and only v8 not v7).

**Comment by magiccreater** [comment]
Hey,

Thanks for quick update.
I configured drupal 7 and import all module and now i got this message "
Error message
IBM APIC Module is not correctly configured. Specify a valid hostname and try again.
".
So where i need to define hostname and other configuration about IBM apic?

thanks
chintan

**Comment by chrisdudley** [comment]
You will not be successful setting this up by hand.
If you want to use the APIC Developer Portal, then download the OVA or use the new kubernetes based containers for v2018.
But I can pretty much guarantee you will not get it working by just installing these modules in a manual Drupal install. It simply won't work.

**Comment by chrisdudley** [comment]
The source for the drupal 8 based APIC v2018 developer portal has now been published to master.
The source for the drupal 7 based APIC v5 developer portal can be found in the APIC_v5 branch.

Note that publishing this source is to make it easier for people to create custom modules, themes, etc.
It is not expected that people will be able to use these files alone to create a portal site - that is not the intention.
Nor do we support anyone making direct edits to any of these files in an APIC deployment - behaviour has to be modified using standard drupal procedures such as hooks and custom modules.

**Comment by magiccreater** [comment]
Hey Chirs,

Thanks you very much for very quick update.
It is really help me a lot to develop theme for IBM developer portal drupal 8 version.

thanks
Chintan

**Comment by chrisdudley** [comment]
Have a look at 

https://www.ibm.com/support/knowledgecenter/en/SSMNED_2018/com.ibm.apic.devportal.doc/tapic_portal_using_subtheme_drupal8.html
and
https://www.ibm.com/support/knowledgecenter/en/SSMNED_2018/com.ibm.apic.devportal.doc/tutorial_portal_customizing_css.html

Use the theme generator to generate a sub-theme and you can then use CSS or SCSS in your sub theme.

We just added the ability to create sub-themes in a variety of colour schemes as a quick starting point - some more tidying up of that generator UI will be done in the next release.

Remember you cannot modify any file we ship - you have to create your own theme or module to modify any behaviour and so to by normal drupal means such as hooks.
