### ISSUE TITLE
Possibility to use alternative content management systems to Drupal or a bare custom approach

### ISSUE THREAD

**Issue by godfrednanaowusu** [ibm-apiconnect/devportal#30]
I will appreciate if more light can be shed on how we could consume this apiconnect without drupal, is there an additional documentation available.

An example is trying to use apiconnect with a framework like Django/Flask etc.
What are the possibilities available please.

**Comment by chrisdudley** [comment]
The API Connect Developer Portal is drupal only, and that's all we support.

If you consult the API Connect documentation you will find references to the APIs available with which you could try to build your own portal. Building and maintaining it would obviously be your responsibility.

**Comment by godfrednanaowusu** [comment]
Thank you for your prompt response.
