### ISSUE TITLE
Syntax error on content refresh

### ISSUE THREAD

**Issue by nevafuse** [ibm-apiconnect/devportal#31]
I noticed after restoring a backup that the People didn't match what was in APIM.

After looking through the logs, I noticed the following error over and over that matches about how many People I should have.

snapshot: Got type: consumer_org
snapshot: Caught exception in drush_ibm_apim_content_refresh: Syntax error [warning]
snapshot: Got type: consumer_org

I tried to enable some of the debug logging but nothing appears to give me anymore information.

Any ideas?  Do you have the same error?  Do I have too many users (2-3k)?  Thanks.

**Comment by chrisdudley** [comment]
You don’t mention what apic version you’re using which makes it rather hard to comment.

I would also point out this is not a support mechanism for api connect.
If you are having issues you must raise a PMR with IBM Support.

No you don’t have too many users, you likely have old code though. Please upgrade to the latest fixpack and if still having issues then contact support.

**Comment by nevafuse** [comment]
I'm on 10.0.1.5-ifix3.  I have an open PMR already - TS007754875.

I was able to turn on tracing (wasn't working before because the process was in an infinite loop so I had to kill it).

Jan 6 15:49:04 [removed] Jan 6 20:49:03 [removed] 545d55c02d4a[1364]: [ queue stderr] 3952012 ef8531:ef8531:0bafb6 2022-01-06 20:49:03: snapshot: WATCHDOG: [DEBUG] [ibm_apim] Drupal\ibm_apim\Service\ApicUserService::getUserFromJSON ENTRY Trace input: N;. | user: anonymous | uri: [removed] | referer: #015
Jan 6 15:49:04 [removed] Jan 6 20:49:03 [removed] 545d55c02d4a[1364]: [ queue stderr] 3952012 ef8531:ef8531:0bafb6 2022-01-06 20:49:03: snapshot: WATCHDOG: [DEBUG] [ibm_apim] Drupal\ibm_apim\Service\ApicUserService::getCustomUserFields ENTRY Trace input: N;. | user: anonymous | uri: [removed] | referer: #015
Jan 6 15:49:04 [removed] Jan 6 20:49:03 [removed] 545d55c02d4a[1364]: [ queue stderr] 3952012 ef8531:ef8531:0bafb6 2022-01-06 20:49:03: snapshot: WATCHDOG: [DEBUG] [ibm_apim] Drupal\ibm_apim\Service\ApicUserService::getCustomUserFields EXIT Trace return: a:3:{i:1;s:32:&quot;field_accept_terms_and_condition&quot;;i:2;s:32:&quot;field_api_transactions_per_month&quot;;i:3;s:24:&quot;field_organization_state&quot;;}. | user: anonymous | uri: [removed] | referer: #015
Jan 6 15:49:04 [removed] Jan 6 20:49:03 [removed] 545d55c02d4a[1364]: [ queue stderr] 3952012 ef8531:ef8531:0bafb6 2022-01-06 20:49:03: snapshot: Caught exception in drush_ibm_apim_content_refresh: Syntax error [warning]

**Comment by chrisdudley** [comment]
Thanks - we've got the PMR.
We've found 2 problems : 
 - The additional metadata you've got on your users is missing from the snapshot api manager is sending the portal
 - The portal needs to be more resilient to handle that data missing

Those issues are being looked into. In the meantime the users will be created when the user next logs in and the fact they're not showing in the portal admin People list should not affect anything.

I am going to close this issue as it can be tracked via the PMR.

**Comment by nevafuse** [comment]
Is there an APAR?

Does login trigger a different process to load the user?  Or does it just ignore the custom fields?  Any other way to trigger that login user load process?

I noticed it seems to work fine when you first enable the portal for a catalog.  Seems like that would use the same process as asking for a new snapshot but maybe not?

Any idea on a quick fix?  Maybe comment out adding the custom fields in that function?  Would the custom fields get added later when they login?  Thanks for your help.

**Comment by redlanne** [comment]
@nevafuse there should be updates regarding an APAR via the case you have raised via IBM support.  

As @chrisdudley had already indicated the users will be created with the user next logs in.  

Please address any further questions via the case.

**Comment by chrisdudley** [comment]
No modifications to any source provided by us would be supported.
As mentioned - there are no functional impacts from the users not showing in the People table therefore there is no requirement for a "quick fix".
The fixes will likely be delivered in the next fixpack - until then just be aware the People list wont necessarily show every user, but thats the limit of the impact here. Short term hacks are neither warranted or supported.
You can still get a complete user listing out of API Manager via its API and CLI, and that's the right way to be listing consumers anyway.
