### ISSUE TITLE
consumerorg module - setting the custom filed from metadata fails for strings

### ISSUE THREAD

**Issue by vvidovic-croz** [ibm-apiconnect/devportal#36]
Bug in the module `consumerorg`, in the source file `src/Service/ConsumerOrgService.php`, function `createFromJSON()` on the line 1998:
```
$org->addCustomField($field, json_decode($json['consumer_org']['metadata'][$field], TRUE, 512, JSON_THROW_ON_ERROR));
```

Basically, this code will fail if we send a string (that can't be converted to some JSON primitive type) in the metadata, for example:
- ""
- "-"
- "abc"

In case the metadata field is a number (for example), it will work fine:
- "123"

As a result, metadata received from the APIM will not be visible as a value of the custom field in the portal.

**Comment by redlanne** [comment]
This code is maintained in an internal repo so the change needs to be made there. Thank you for bringing this to our attention.
