### ISSUE TITLE
Mail Subscribers module bugfix

### ISSUE THREAD

**Issue by andrewfandrew** [ibm-apiconnect/devportal#44]
On a V10 (Drupal 9) portal site, log in as superuser or admin user. Enable Database logging i.e. enable the 'dblog' module. Navigate to /admin/config/system/mail_subscribers. This leads to a white screen. Then navigate to /admin/reports/dblog. Choose the last log message which is an error message.

I have applied a fix to the admin form of the module as PR #43.

I have also raised an issue for this on drupal.org: https://www.drupal.org/project/mail_subscribers/issues/3354068#comment-15009848

**Comment by redlanne** [comment]
@andrewfandrew thank you - I have handled this internally from the support ticket previously raised.  This will be fixed in our next release.
