### ISSUE TITLE
Show password icon repeating 

### ISSUE THREAD

**Issue by TurquoiseSparkle** [ibm-apiconnect/devportal#47]
The show password icon (same behaviour on various fields throughout the portal e.g login form, change password form, create app form in the credentials field) repeats. Using V10.0.5.1
Steps to reproduce 1) use edge or chrome, doesn't occur in Firefox. 2) navigate to log in form. 3) navigate away from screen to any other page. 4) use the browser's back button to go back to the log in form.
See also https://www.drupal.org/project/view_password/issues/3324094

**Comment by chrisdudley** [comment]
Please retry using 10.0.5.6, there really isn’t any point in reporting issues on ancient versions from almost 2 years ago.

Please reopen - or raise a proper IBM Support PMR if still an issue with latest code.
