### ISSUE TITLE
Credentials copied tooltip not displaying

### ISSUE THREAD

**Issue by TurquoiseSparkle** [ibm-apiconnect/devportal#48]
On the create new app and edit app screens the copy credentials button works to copy the credentials, but the bootstrap tooltip saying they were successfully copied doesn't display. Using v10.0.5.1.
Steps to reproduce: create or edit an app 2) click the copy icon next to the client I'd field 3) observe that the data is in the clipboard, but no tooltip was displayed

**Comment by chrisdudley** [comment]
Please retry using 10.0.5.6, there really isn’t any point in reporting issues on ancient versions from almost 2 years ago.

Please reopen - or raise a proper IBM Support PMR if still an issue with latest code.
