### ISSUE TITLE
hook_apic_app_image_delete not invoked when removing application image

### ISSUE THREAD

**Issue by elisherer** [ibm-apiconnect/devportal#5]
I checked the code and and it appears that the native way of removing an image
(through [devportal/apic_app/src/Form/UploadImageForm.php](https://github.com/ibm-apiconnect/devportal/blob/master/apic_app/src/Form/UploadImageForm.php) clicking the remove button) does not trigger the `hook_apic_app_image_delete`.
However, it is invoked if you browse to the URL [<portal>/application/{app_id}/removeimage] (not linked by any page) which uses [devportal/apic_app/src/Form/RemoveImageForm.php](https://github.com/ibm-apiconnect/devportal/blob/master/apic_app/src/Form/RemoveImageForm.php).

**Comment by chrisdudley** [comment]
Thanks - you're completely correct. The fix for this will be in the next fixpack (due in a few weeks).

**Comment by chrisdudley** [comment]
This has now been fixed in APIC 2018.4.1.6.
