### ISSUE TITLE
apic_app_subscribe() showing Argument Count Error 

### ISSUE THREAD

**Issue by shuhaibofficial** [ibm-apiconnect/devportal#9]
https://github.com/ibm-apiconnect/devportal/blob/9c5985ea2e7434794b8ca0e42a1008596f563ba6/apic_app/apic_app.api.php#L180

ArgumentCountError: Too few arguments to function moduleName_apic_app_subscribe(), 4 passed and exactly 6 expected
$subId is missing and another Argument also

**Comment by shuhaibofficial** [comment]
$subId and $product_url is not available.
why?

**Comment by shuhaibofficial** [comment]
Error Trace:

send_sub_data_apic_app_subscribe(Object, Array, '/consumer-api/apps/842d4ac9-cfb3-452f-8253-7fcaeaad9d53/1a93c00c-cb40-4ecc-a38f-c3db2e64074d', '/consumer-api/products/a962c0b9-6158-42dd-bae9-a9c23af424d4:default')

**Comment by chrisdudley** [comment]
What version of APIC are you using?
I would strongly recommend upgrading to 2018.4.1.10 which has just been released as there were some fixes made in the hook code in the latest fixpack.
I can't guarantee it will resolve your problem though.

**Comment by chrisdudley** [comment]
You could also enable entry exit trace and see whats being fed into the `subscribeToPlan` function.
You can enable it from Configuration->Development->IBM Development.

The arguments to subscribeToPlan should be the appUrl and the planId where the planId should be the product_url:planName.

See if that helps debug whats going on ?

**Comment by chrisdudley** [comment]
And for the future if you open a new issue for the same problem as an existing one you opened, please at least link them together or something. Though im not sure why you created a new issue here at all. I've now closed the other one you raised.

**Comment by shuhaibofficial** [comment]
> What version of APIC are you using?
> I would strongly recommend upgrading to 2018.4.1.10 which has just been released as there were some fixes made in the hook code in the latest fixpack.
> I can't guarantee it will resolve your problem though.

_**IBM API Connect Version**_
**2018.4.1.3**
20190301-2216
API Explorer
4.1.38
Tue Feb 12 2019 15:13:58 GMT+0000 (GMT)
 
Drupal Version
8.6.10

 
Web Server
nginx/1.10.3
 
PHP
Version
7.1.26-1+ubuntu16.04.1+deb.sury.org+1 (more information)
Memory limit
512M
 
Database
Version
5.7.24-26-57-log
System
MySQL, MariaDB, Percona Server, or equivalent

**Comment by shuhaibofficial** [comment]
> And for the future if you open a new issue for the same problem as an existing one you opened, please at least link them together or something. Though im not sure why you created a new issue here at all. I've now closed the other one you raised.

This my First Issue in Github. I have first created that issue because the hooks is causing failure ,after i found that the issue with args passing to the hooks , i forgot to link  them.
Next time i will keep the standards for opening an issue

**Comment by chrisdudley** [comment]
2018.4.1.3 is very old now.
I suggest you upgrade to 2018.4.1.10 before doing anything else.

We wont be able to assist further until you do.

Please see if you can recreate on 2018.4.1.10, i suspect you'll find it will fix your problem. If it doesn't then you can reopen this bug.
